In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


np.byte	signed char ---> Platform-defined
np.ubyte ---> unsigned char
np.intc	int	Platform-defined
np.uintc	unsigned int	Platform-defined
np.int_	long	Platform-defined
np.uint	unsigned long

In [3]:
x = np.float32(3)
x

3.0

In [7]:
x.dtype

dtype('float32')

In [8]:
c = np.int_(55)
c

55

In [9]:
c.dtype

dtype('int32')

In [10]:
a = np.arange(3,dtype=np.float64)
a

array([0., 1., 2.])

In [12]:
a.astype(np.int16)

array([0, 1, 2], dtype=int16)

In [17]:
cc= np.csingle(a)
cc

array([0.+0.j, 1.+0.j, 2.+0.j], dtype=complex64)

In [15]:
c = np.cdouble(a)
c

array([0.+0.j, 1.+0.j, 2.+0.j])

In [18]:
cc.dtype

dtype('complex64')

In [16]:
c.dtype

dtype('complex128')

In [19]:
d = np.dtype('int')
d

dtype('int32')

In [23]:
np.issubdtype(d,'float')

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Conversion of the second argument of issubdtype from `'float'` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype('float').type`.
  """Entry point for launching an IPython kernel.


False

In [24]:
np.issubdtype(d,'int')

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Conversion of the second argument of issubdtype from `'int'` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int32 == np.dtype('int').type`.
  """Entry point for launching an IPython kernel.


True

In [26]:
np.power(2,3, dtype= np.float64)

8.0

In [27]:
np.iinfo(np.int)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [28]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [32]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

np.intp	intptr_t	Integer used for indexing, typically the same as ssize_t
np.uintp	uintptr_t	Integer large enough to hold a pointer

In [36]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [37]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])